## **Array indexing**
### **Slice indexing:**
Similar to the use of slice indexing with lists and strings, we can use slice indexing to pull out subregions of ndarrays.

In [13]:
import numpy as np

# rank 2 array of shape (3,4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])

print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Use **array slicing** to get a subarray consisting of the firs 2 rows X 2 columns.

**syntax for slicing:**
> obj[start:stop:step]

**Ex:**
```Python
py_string = 'Python'

print(py_string[0:3])  

# Pyt
```

In [14]:
a_slice = an_array[:2, 1:3]

print(a_slice)

[[12 13]
 [22 23]]


---

![](../Week-3-2-numpy_satellite/Screenshot_6.png)

---

**When you modify a slice, you** actually **modify the underlying array**.

In [15]:
print(f'Before: {an_array[0, 1]}') # inspect the element at 0, 1

a_slice[0, 0] = 1000 # a_slice [0, 0] is the same piece of data as an_array[0, 1]

print(f'After: {an_array[0, 1]}')

Before: 12
After: 1000


### **Use both integer indexing & slice indexing**
We can use combinations of integer indexing and slice indexing to create different shaped matrices.

In [16]:
# create a Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])

print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


**numpy.shape** - _размеры массива, его форма_. 
> Это кортеж натуральных чисел, показывающий длину массива по каждой оси.</br>**Для матрицы из n строк и m столбов, shape будет (n,m)**. </br>Число элементов кортежа shape равно рангу массива, то есть ndim.

In [17]:
# use both integer indexing & slicing generates an array of lower rank
row_rank1 = an_array[1, :] # rank 1 view

print(row_rank1, row_rank1.shape) # notice only a single []

[21 22 23 24] (4,)


In [18]:
# slicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2, :] # rank 2 view

print(row_rank2, row_rank2.shape) # notice the [[]]

[[21 22 23 24]] (1, 4)


In [19]:
# we can do the same thing for columns of an array:
print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape) # rank 1
print()
print(col_rank2, col_rank2.shape) # rank 2


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


### Array indexing for changing elements
Sometimes it's useful to use an array of indexes to access or change elements.

In [20]:
# create a new array
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

print(f'Original array:\n{an_array}')

Original array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


**arange()** - это одна из процедур создания массива, основанная на числовых диапазонах. </br>Он создает экземпляр ndarray с **равномерно распределенными значениями** и возвращает ссылку на него.

**Ex:**
```Python 
# np.arange(start=1, stop=10, step=3)
# array([1, 4, 7])
```

In [21]:
# create an array of indices
col_indices = np.array([0,1,2,0]) # create a rank 1 array

print(f'Col indices picked:\n {col_indices}')

row_indices = np.arange(4)

print(f'Rows indices picked:\n {row_indices}')

Col indices picked:
 [0 1 2 0]
Rows indices picked:
 [0 1 2 3]


### python**(zip)**
В Pyhon функция **zip позволяет пройтись одновременно по нескольким итерируемым объектам** (спискам и др.):

**Ex:**
```Python
a = [10, 20, 30, 40]
b = ['a', 'b', 'c', 'd', 'e']
for i, j in zip(a, b):
    print(i, j)
    
# 10 a
# 20 b
# 30 c
# 40 d    
```

In [22]:
# example the pairings of row_inices and col_indices. These are the elements we'll change next.
for row, col in zip(row_indices, col_indices):
    print(f'{row}, {col}')

0, 0
1, 1
2, 2
3, 0


In [23]:
# select one element from each row
print(f'values in the array at those indices: {an_array[row_indices, col_indices]}')

values in the array at those indices: [11 22 33 41]


In [24]:
# change one element from each row using the indices selected
an_array[row_indices, col_indices] += 10000

print(f'Changed array:\n {an_array}')

Changed array:
 [[10011    12    13]
 [   21 10022    23]
 [   31    32 10033]
 [10041    42    43]]
