---
> # Numpy, Broadcasting
---
_The term **broadcasting** refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations.<br>Arithmetic operations on arrays are usually done on corresponding elements.<br>If two arrays are of exactly the same shape, then these operations are smoothly performed._

If the dimensions of two arrays are dissimilar, element-to-element operations are not possible.<br>However, operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability.<br>The smaller array is broadcast to the size of the larger array so that they have compatible shapes.

In [1]:
import numpy as np

In [2]:
start = np.zeros((4,3)) # create an ndarray filled with zeros
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])

print(add_rows)

[1 0 2]


In [5]:
y = start + add_rows # add to each row of 'start using broadcasting

print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [6]:
# creat an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [7]:
# add to each column of 'start' using broadcasting
y = start + add_cols

print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [9]:
# this will just broacast in both dimensions
add_scalar = np.array([1])

print(start + add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
a = np.array([[0,0],[0,0]])
b1 = np.array([1,1])
b2 = 1

# a+b1 and a+b2 result in the same matrix.
print(a + b1)
print()
print(a + b2)

[[1 1]
 [1 1]]

[[1 1]
 [1 1]]
