## Imports
So far we've talked about types and functions which are built-in to the language.\
But one of the best things about Python (especially if you're a data scientist) \
is the vast number of high-quality custom libraries that have been written for it.

In [1]:
# import

import math
print(f'It\'s math! It has tyype {type(math)}')

It's math! It has tyype <class 'module'>


`math` is a module.\
A module is just a collection of variables (a namespace) defined by someone else.\
We can see all the names in `math` using the built-in function `dir()`.

In [2]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


We can access these variables using dot syntax. Some of them refer to simple values, like `math.pi`:

In [11]:
print(f'pi to 4 significant digits = {math.pi :.4}') # :.4 - вывод до четвертого знака после запятой.

pi to 4 significant digits = 3.142


In [12]:
# math function
math.log(32, 2) # Return the logarithm of x to the given base.

5.0

In [13]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



We can also call `help()` on the module itself.\
This will give us the combined documentation for all the functions and values in the module `math`

In [71]:
# help(math)

# Help on built-in module math:

# NAME
#     math

# DESCRIPTION
#     This module provides access to the mathematical functions
#     defined by the C standard.

### Other import syntax
If we know we'll be using functions in `math` frequently we can import it under\
a shorter alias to save some typing.

In [18]:
import math as mt

print(f'{mt.pi :.4}')

3.142


Wouldn't it be great if we could refer to all the variables in the `math` module\
by themselves? i.e. if we could just refer to `pi` instead of `math.pi` or `mt.pi`?\
We can do that.

In [33]:
from math import *

print(f'pi = {pi :.4}\nlog(base 2)32 = {log(32, 2)}')

pi = 3.142
log(base 2)32 = 5.0


### Submodules
We've seen that modules contain variables which can refer to functions or values.\
Something to be aware of is that they can also have variables referring to other modules.

In [41]:
import numpy
print(f'numpy.random is a {type(numpy.random)}')
print(f'it contains names such as ... {dir(numpy.random)[40:]}') # [40:] - вывести срез элементов с 40 до последнего.

numpy.random is a <class 'module'>
it contains names such as ... ['geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'print_function', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf']


So if we import `numpy` as above, then calling a function in the `random` "submodule" will require *two* dots.

In [49]:
# roll 10 dice
rolls = numpy.random.randint(low=1, high=6, size=10)
rolls

array([4, 1, 5, 4, 4, 2, 3, 5, 1, 5])

## Three tools for understanding strange objects.

1. `type()` (what is this thing?)

In [50]:
type(rolls)

numpy.ndarray

2.`dir()` (what can I do with it?)

In [51]:
print(dir(rolls))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [55]:
# What am I trying to do with this dice roll data? Maybe I want the average roll, in which case the "mean
# Method looks promising...
rolls.mean() # mean of array ([4, 1, 5, 4, 4, 2, 3, 5, 1, 5]) values.

3.4

In [56]:
# Or maybe I just want to get back on familiar ground, in which case I might want to check out "tolist"
rolls.tolist()

[4, 1, 5, 4, 4, 2, 3, 5, 1, 5]

3. `help()` (tell me more)

In [58]:
# That "ravel" attribute sounds interesting.
help(rolls.ravel)

Help on built-in function ravel:

ravel(...) method of numpy.ndarray instance
    a.ravel([order])
    
    Return a flattened array.
    
    Refer to `numpy.ravel` for full documentation.
    
    See Also
    --------
    numpy.ravel : equivalent function
    
    ndarray.flat : a flat iterator on the array.



In [67]:
# Okay, just tell me everything there is to know about numpy.ndarray

# help(rolls)
# >>>
#  |  An array object represents a multidimensional, homogeneous array
#  |  of fixed-size items.  An associated data-type object describes the
#  |  format of each element in the array (its byte-order, how many bytes it
#  |  occupies in memory, whether it is an integer, a floating point number,
#  |  or something else, etc.)
#  |  
#  |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
#  |  to the See Also section below).  The parameters given here refer to
#  |  a low-level method (`ndarray(...)`) for instantiating an array.
#  |  
#  |  For more information, refer to the `numpy` module and examine the
#  |  methods and attributes of an array.

### Operator overloading
It's an error!!!

In [78]:
rolls + 10

array([14, 11, 15, 14, 14, 12, 13, 15, 11, 15])

In [80]:
# At which indices are the dice less than or  equal to 3?
print(rolls)
rolls <= 3

[4 1 5 4 4 2 3 5 1 5]


array([False,  True, False, False, False,  True,  True, False,  True,
       False])

In [86]:
# Create a 2-dimensional array
xlist = [[1,2,3],[2,4,6],]
x = numpy.asarray(xlist)
print(f"xlist = {xlist}\nx = \n{x}")

xlist = [[1, 2, 3], [2, 4, 6]]
x = 
[[1 2 3]
 [2 4 6]]


In [88]:
# Get the last element of the second row of our numpy array?
x[1, -1] # вывод последнего элемента из вложенного списка с индексом "1"

6

In [90]:
# Get the last element of the second sublist of our nested list?
# xlist[1, -1] # вывод последнего элемента из вложенного списка с индексом "1"

#>>>
# TypeError: list indices must be integers or slices, not tuple

numpy's `nsarray` type is specialized for working with multi-dimensional data,\n
so it defines its own logic for indexing, allowing us to index by a tuple to specify the index at each dimension.

### When does 1 + 1 not equal 2?


In [91]:
import tensorflow as tf
# Create two constants, each with value 1
a = tf.constant(1)
b = tf.constant(1)
# Add them together to get...
a + b

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [95]:
help(dir(list))

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

This turns out to be directly related to operator overloading.

When Python programmers want to define how operators behave on their types, they do so by implementing\
methods with special names beginning and ending with 2 underscores such as `__lt__`, `__setattr__`, or `__contains__`.\
Generally, names that follow this double-underscore format have a special meaning to Python.

So, for example, the expression `x in [1, 2, 3]` is actually calling the list method `__contains__` behind-the-scenes.\
It's equivalent to (the much uglier) `[1, 2, 3].__contains__(x)`.

If you're curious to learn more, you can check out Python's official documentation, which describes many, many more of these special "underscores" methods.
https://docs.python.org/3.4/reference/datamodel.html#special-method-names

In [97]:
x = 2
arr = [1, 2, 3]
x in arr

True

In [98]:
arr.__contains__(x)

True