---
> # **The N-dimensional array** (_ndarray_)
---

An ndarray is a (usually fixed-size) multidimensional container of items of the same type and size. 
</br>Основным объектом **NumPy** является однородный многомерный массив (**в numpy называется numpy.ndarray**).</br>Это многомерный массив элементов (обычно чисел), одного типа.


In [1]:
import numpy as np

an_array = np.array([3, 33, 333]) # create a rank 1 array

print(type(an_array)) # the type of an ndarray is: <class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [2]:
# test the shape of the array we just created, it should have just one dimension
print(an_array.shape)

(3,)


In [3]:
# because this is a 1-rank array, we need only one index to access rach element
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [4]:
an_array[0] = 888

print(an_array)

[888  33 333]


### **How to create a Rank 2 numpy array:**

A rank 2 **ndarray** is one with two dimensions. Notice the format below of **[[row, [row]]**.</br>2 dimensional arrays are great for representing matrices which are oftern useful in data dcience.

In [5]:
another = np.array([[11, 12, 13], [21, 22, 23]])

print(another)
print("The shape is 2 rows, 3 columns: ", another.shape) # rows x columns
print("Accessing elements [0, 0], [0, 1], and [1, 0] of the ndarray", another[0, 0], another[0, 1], another[1, 0])

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns:  (2, 3)
Accessing elements [0, 0], [0, 1], and [1, 0] of the ndarray 11 12 21


### **There are many way to create numpy arrays:**
Here we create a number of different size arrays with different shapes and different pre-filled values.</br>Numpy has a number of built in methods which halp us quiclky and easily create multidimensional arrays.

In [6]:
import numpy as np
# create a 2x2 array of zeros
ex1 = np.zeros((2, 2))

print(ex1)

[[0. 0.]
 [0. 0.]]


In [7]:
# create a 2x3 array filled with 9.0
ex2 = np.full((2,3), 9.0)

print(ex2)

[[9. 9. 9.]
 [9. 9. 9.]]


In [8]:
# create a 6x6 matrix with the diagonal 1s and the others 0
# Что делать, если вы хотите создать матрицу n на n где диагонали все едины, а все остальные значения равны нулю?
ex3 = np.eye(6,6)

print(ex3)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [9]:
# create an array of ones
ex4 = np.ones((1,2))

print(ex4)

[[1. 1.]]


In [10]:
# create an array of random floats between 0 and 1
ex5 = np.random.random((2,2))

print(ex5)

[[0.3712902  0.03351908]
 [0.36537313 0.66252519]]


### **Зачем нужны матрицы?**
Основным применением матриц было решение линейных уравнений.</br>Матрицы широко применяются в математике для компактной записи систем линейных алгебраических или дифференциальных уравнений.</br>В этом случае, количество строк матрицы соответствует числу уравнений, а количество столбцов — количеству неизвестных.