In [1]:
import numpy as np

In [2]:
an_array = np.array([[11, 12], [21, 22], [31, 32]])

print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [3]:
# create a filter which will be boolean values for whether each element meets
filter = (an_array > 15)

filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

Notice that the filter is a same size ndarray as an_array which is filled with **True** for each element whose correspondig element in an_array which is greater than 15 and **False** those elements whose value is less than 15.

In [4]:
# we can now select just those elements which meet that criteria
print(an_array[filter])

[21 22 31 32]


In [5]:
# for short
print(f'Values which more than 15: an_array[an_array > 15]')

# and all value in range
print(f'Values in range 20 to 30: {an_array[(an_array > 20) & (an_array < 30)]}')

# print all even values
print(f'All even value from array: {an_array[an_array % 2 == 0]}')

Values which more than 15: an_array[an_array > 15]
Values in range 20 to 30: [21 22]
All even value from array: [12 22 32]


What is particularly useful is that we can actually change elements in the array applying a similar logical filter. Let's **add 100 to all the even values**.

In [6]:
an_array[an_array % 2 == 0] += 100

print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]
