In [1]:
import numpy as np

### Datatypes:

In [3]:
ex1 = np.array([11,12])
print(ex1.dtype)

int32


In [4]:
ex2 = np.array([11.0, 12.0])
print(ex2.dtype)

float64


In [6]:
ex3 = np.array([11,21], dtype = np.int64)
print(ex3.dtype)

int64


In [8]:
ex4 = np.array([11.1,12.7], dtype = np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


### Arithmetic array operations

In [10]:
x = np.array([[111, 112], [121, 122]], dtype = np.int)
y = np.array([[211.1, 212.1], [221.1, 222.1]], dtype = np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [12]:
# add
print(x + y) # the plus sign works
print()
print(np.add(x, y)) # so does the numpy function 'add'

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [13]:
# substruct
print(x - y) # the minus sign works
print()
print(np.subtract(x, y)) # so does the numpy function 'substract'

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [14]:
# multiply
print(x * y) # the multiply sign works
print()
print(np.multiply(x, y)) # so does the numpy function 'multiply'

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [15]:
# divide
print(x / y) # the divide sight works
print()
print(np.divide(x, y)) # so does the numpy function 'divide'

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [16]:
# square root
print(np.sqrt(x))
print()
print(np.sqrt(y))

[[10.53565375 10.58300524]
 [11.         11.04536102]]

[[14.52928078 14.56365339]
 [14.86943173 14.90301983]]


In [17]:
# exponent (e ** x)
print(np.exp(x))
print()
print(np.exp(y))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]

[[4.78151068e+91 1.29974936e+92]
 [1.05319781e+96 2.86288848e+96]]
